app = "din-app-navn"

[build]
  builder = "Docker"

[env]
  DJANGO_SETTINGS_MODULE = "dinprojekt.settings"
  DEBUG = "False"

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
