# fly.toml app configuration file generated for ideer-til-dark-morning-5968 on 2025-06-30T22:55:52+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ideer-til"

[env]
  DEBUG = "False"

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
